name: MacOS

on:
  push:
    branches:  [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    steps:
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.3.1

    - name: Brew install
      run: |
         brew install bison flex binutils libffi double-conversion boost jemalloc fmt glog gnu-sed bash zlib ncurses
         echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

    - name: Install gem
      run: gem install tebako

    - name: Checkout sample
      uses: actions/checkout@v4

    - name: Package
      run: tebako press -e app.rb -o sample.tebako -r sinatra

    - name: Look around
      run: ls -la
