name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/cache@v4
      id: cache-win
      with:
        path: D:/a/_temp/msys64/home/runneradmin/.tebako
        key: windows-latest
    - name: install ${{runner.os}} deps
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        path-type: minimal
        update: true
        install: >-
          git
          tar
          bison
          flex
        pacboy: >-
          cmake:p
          boost:p
          diffutils:p
          libevent:p
          double-conversion:p
          fmt:p
          glog:p
          dlfcn:p
          ninja:p
          gtest:p
          autotools:p
          ncurses:p
          ruby:p
          toolchain:p
          openssl:p
          make:p
          libyaml:p
          libxslt:p
          postgresql:p
          libmariadbclient:p

    - name: Install gem
      run: gem install tebako

    - name: Checkout sample
      uses: actions/checkout@v4

    - name: Package
      run: tebako press -e app.rb -o sample.tebako -r sinatra

    - name: Look around
      run: ls -la

    - name: Start packaged Sinatra application
      run: |
        nohup ./sample.tebako.exe mock-service -p 4567 &
        echo "PID=$PID" >> $GITHUB_ENV

    - name: Wait for Sinatra to start
      run: sleep 15

    - name: Place GET request
      run: curl http://localhost:4567

    - name: End Sinatra application
      run: kill -9 $PID
